/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.promasys.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.promasys.domain.Meeting;
import com.promasys.service.inter.MeetingServiceInter;
import com.promasys.struts.form.MeetingForm;

public class InformAction extends DispatchAction {

	MeetingServiceInter meetingService;
	
	public MeetingServiceInter getMeetingService() {
		return meetingService;
	}


	public void setMeetingService(MeetingServiceInter meetingService) {
		this.meetingService = meetingService;
	}


	public ActionForward InformUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return mapping.findForward("goInformUI");
	}
	
	
	public ActionForward meeting(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		MeetingForm meetingForm = (MeetingForm) form;
		Meeting meeting = new Meeting();
		meeting.setTopic(meetingForm.getTopic());
		meeting.setTime(meetingForm.getTime());
		meeting.setSite(meetingForm.getSite());
		meeting.setStaffs(meetingForm.getStaffs());
		meeting.setSetTime(new java.util.Date());
		meetingService.save(meeting);
		request.getSession().setAttribute("meeting", meeting);
		return mapping.findForward("goHomeUI");
	}
}
