/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.promasys.struts.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.promasys.service.inter.DocServiceInter;
import com.promasys.service.inter.UserServiceInter;
import com.promasys.domain.Users;
import com.promasys.struts.form.UserForm;

public class LoginAction extends DispatchAction {

	private UserServiceInter userService;
	private DocServiceInter docService;
	

	public DocServiceInter getDocService() {
		return docService;
	}

	public void setDocService(DocServiceInter docService) {
		this.docService = docService;
	}

	public UserServiceInter getUserService() {
		return userService;
	}

	public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}

	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;
//		return mapping.findForward("goHomeUI");
		Users user = new Users();
//		System.out.println("hello");
		user.setName(userForm.getName());
		user.setPwd(userForm.getPwd());
//		System.out.println("name="+userForm.getName()+" pwd="+userForm.getPwd());
		user = userService.check(user);
		if(user!=null){
			//用户合法，必须把该用户bean放入session域对象
			Date date = new Date();
//			System.out.println(date);
			user.setLoginDate(date);
//			System.out.println(user.getLoginDate());
			userService.update(user);
			request.getSession().setAttribute("loginuser", user);
			request.setAttribute("prodoclist", docService.getResult("from Prodoclist", null));
			request.setAttribute("crewlist", userService.getResult("from Users", null));
			return mapping.findForward("goHomeUI");
		}else{
			//用户不合法
			return mapping.findForward("loginUI");
		}
	}
	
	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//把当前网站的session清空
		request.getSession().invalidate();
		return mapping.findForward("loginUI");
	}
}