/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.promasys.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.bsf.util.event.adapters.java_awt_event_ActionAdapter;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.promasys.domain.Posts;
import com.promasys.domain.Users;
import com.promasys.service.impl.PostsServiceImpl;
import com.promasys.service.inter.PostsServiceInter;
import com.promasys.struts.form.ForumForm;

public class PostingAction extends DispatchAction {

	private PostsServiceInter postsService;
	
	public PostsServiceInter getPostsService() {
		return postsService;
	}

	public void setPostsService(PostsServiceInter postsService) {
		this.postsService = postsService;
	}

	public ActionForward postingUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		return mapping.findForward("goPostingUI");
	}
	
	public ActionForward ForumUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//获得当前用户
		Users loginuser = (Users) request.getSession().getAttribute("loginuser");
		//获得表单
		ForumForm forumForm = (ForumForm) form;
		
		Posts posts = new Posts();
		posts.setName(forumForm.getName());
		posts.setContent(forumForm.getContent());
		posts.setPostTime(new java.util.Date());
		posts.setUsers(loginuser);
		//保存posts
		postsService.save(posts);
		return mapping.findForward("goForumUI");
	}
}