/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.promasys.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.upload.FormFile;

import com.promasys.domain.Prodoclist;
import com.promasys.domain.Users;
import com.promasys.service.inter.DocServiceInter;
import com.promasys.service.inter.UserServiceInter;
import com.promasys.struts.form.UserForm;
import com.promasys.utils.MyTools;


public class UploadDocAction extends DispatchAction {

	private DocServiceInter docService;
	private UserServiceInter userService;
	
	public UserServiceInter getUserService() {
		return userService;
	}

	public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}

	public DocServiceInter getDocService() {
		return docService;
	}

	public void setDocService(DocServiceInter docService) {
		this.docService = docService;
	}

	public ActionForward uploadDoc(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//获得当前用户
		Users loginUser = (Users) request.getSession().getAttribute("loginuser");
		//从action中获得表单form
		UserForm userForm = (UserForm) form;
		FormFile docFile = userForm.getDocFile();
		String fileName = docFile.getFileName();
		String fileType = fileName.substring(fileName.indexOf(".")+1);
		int fileSize = docFile.getFileSize();
		//需要再建项目文件表
		Prodoclist doc = new Prodoclist();
		doc.setUsers(loginUser);
		doc.setUploadDate(new java.util.Date());
		doc.setName(fileName);
		doc.setType(fileType);
		doc.setSize(fileSize);
		//把文件上传到服务器的某个文件下/promasys/documents/用户编号/文件类型/doc
		MyTools.uploadDoc(request, docFile, loginUser.getId()+"");
		//保存文件
		docService.save(doc);
		return mapping.findForward("backToUpload");
//		return mapping.getInputForward();
	}
	
	public ActionForward uploadPhoto(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//获得当前用户
		Users loginUser = (Users) request.getSession().getAttribute("loginuser");
		//从action中获得表单form
		UserForm userForm = (UserForm) form;
		FormFile myPhoto = userForm.getMyPhoto();
		
		//把文件上传到服务器的某个文件下/promasys/documents/用户编号/文件类型/doc
		String fileName = MyTools.uploadDoc(request, myPhoto, loginUser.getId()+"");
		//更新头像
		loginUser.setPhoto(fileName);
		//更新对应数据库
		userService.update(loginUser);
		return mapping.findForward("backToUpload");
//		return mapping.getInputForward();
	}
}